/**
 * @orvix/db — re-exports the generated Prisma types.
 *
 * Generated types are produced by `prisma generate` and live in
 * `node_modules/.prisma/client`. We re-export from here so application
 * code can import `@orvix/db/types` rather than reaching into
 * node_modules.
 *
 * Phase 0 imports model and enum types. Once generated, this file is
 * regenerated by the codegen hook (Phase 0 M0.4).
 */

// The re-export below is intentionally a placeholder until generation
// runs. Add the actual re-exports at first generation; for now the
// symbols are declared as type aliases so callers can write
// `import type { ... } from "@orvix/db/types"` without runtime imports.

export type TenantClass = "shared" | "dedicated" | "regional";
export type WorkspaceStatus = "pending" | "composing" | "verifying" | "live" | "paused";
export type DnaStatus = "draft" | "verified" | "live" | "superseded" | "rolled_back";
export type AiAutonomyLevel = "suggest_only" | "suggest_and_act_low_risk";
export type AiTonePreset = "warm_concise" | "concise_direct" | "warm_empathetic";
export type AiMemoryLayer = "short_term" | "long_term" | "organizational";
export type AiRunKind = "suggestion" | "draft" | "action" | "summary" | "briefing" | "inference";
export type AiRunModelTier = "fast" | "medium" | "heavy";
export type AiRunStatus =
  | "queued"
  | "running"
  | "succeeded"
  | "failed"
  | "denied_by_policy"
  | "awaiting_approval";
export type WorkItemPriority = "p0" | "p1" | "p2" | "p3";
export type RoleKey =
  | "owner"
  | "admin"
  | "operator"
  | "member"
  | "viewer"
  | "ai_assistant";
