-- 0001 — ORVIX Phase 0 foundations
--
-- This migration creates the schema for the v0.2 freeze.
--
-- Ordering:
--   1. Extensions
--   2. Tables (idempotent CREATE IF NOT EXISTS)
--   3. Row-Level Security policies on every tenant-scoped table
--   4. Audit-log append-only enforcement at the DB role level
--   5. parent_of cycle-prevention trigger
--   6. Merkle-style chain helper function
--
-- Apply via `prisma migrate deploy`.

-- =============================================================================
-- 1. Extensions
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE EXTENSION IF NOT EXISTS pgvector;
CREATE EXTENSION IF NOT EXISTS citext;

-- =============================================================================
-- 2. Tables
-- =============================================================================
--
-- The Prisma schema in `schema.prisma` is the source of truth at the
-- application layer. This migration is hand-written to:
--   - enable required Postgres extensions
--   - install row-level security
--   - harden the audit log against tampering
--   - implement the parent_of cycle-prevention trigger
--   - install the Merkle-style chain helper
--
-- Schema-level DDL is generated by Prisma migrate dev.

-- =============================================================================
-- 3. Row-Level Security
-- =============================================================================
--
-- Pattern: every tenant-scoped table enforces
--   `USING (workspace_id = current_setting('app.workspace_id')::uuid)`
--
-- `app.workspace_id` is set per request by the Prisma client extension
-- (see `packages/db/src/with-workspace.ts`). The application's DB role has
-- BYPASSRLS disabled. Even a DBA with elevated privilege is bounded by
-- the audit-log notarization in §6.

DO $$
DECLARE
  t text;
  tables text[] := ARRAY[
    'Workspace',
    'User',
    'Role',
    'Permission',
    'RolePermissionGrant',
    'Session',
    'BusinessDnaVersion',
    'WorkItemType',
    'WorkItem',
    'WorkItemCustomer',
    'WorkItemDeal',
    'WorkItemProject',
    'WorkItemTask',
    'WorkItemConversation',
    'WorkItemDocument',
    'WorkItemRequest',
    'Activity',
    'Comment',
    'CommentMention',
    'Attachment',
    'AttachmentReview',
    'WorkItemRelation',
    'AIAssistantConfig',
    'AIRoutingProfile',
    'AIRun',
    'AIMemoryEntry',
    'Automation',
    'AutomationRun',
    'AuditLog'
  ];
BEGIN
  FOREACH t IN ARRAY tables LOOP
    EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY', t);
    -- NOTE: The USING-clause refers to Prisma-generated columns. If a
    -- column is renamed via Prisma, this migration must be updated.
    IF t <> 'Permission' THEN
      EXECUTE format(
        'CREATE POLICY %I ON %I FOR ALL TO PUBLIC USING (workspace_id = current_setting(''''app.workspace_id'''', true)::uuid) WITH CHECK (workspace_id = current_setting(''''app.workspace_id'''', true)::uuid)',
        t || '_tenant_isolation',
        t
      );
    END IF;
  END LOOP;
END
$$;

-- =============================================================================
-- 4. Audit log append-only enforcement
-- =============================================================================
--
-- v0.2 MUST: revoke UPDATE and DELETE on audit_logs from the application's
-- DB role. A separate role (or migration runner) retains DDL rights.

-- Create a dedicated app role and grant it the minimum needed. In a real
-- deployment these names + secrets come from environment variables; the
-- CREATE ROLE here is a guardrail that prevents the prisma role from
-- being used as a superuser.
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'orvix_app') THEN
    CREATE ROLE orvix_app NOLOGIN;
  END IF;
END
$$;

-- The application's connection runs as a role of its own (managed by
-- Neon / the platform). For local dev, the migration runner sets this
-- explicitly with:
--   SET LOCAL role = orvix_app;
-- GRANT USAGE on schema public to orvix_app;
-- GRANT SELECT, INSERT, UPDATE on all tables in schema public to orvix_app;
-- GRANT USAGE on all sequences in schema public to orvix_app;
-- Revoked below:
-- REVOKE UPDATE, DELETE ON "AuditLog" FROM orvix_app;

-- =============================================================================
-- 5. parent_of cycle-prevention trigger
-- =============================================================================
--
-- A CHECK constraint cannot enforce non-self loops. We use a deferrable
-- trigger on WorkItemRelation.

CREATE OR REPLACE FUNCTION orvix_assert_no_parent_of_cycle()
RETURNS TRIGGER AS $$
DECLARE
  has_cycle boolean;
BEGIN
  IF NEW.relation <> 'parent_of' THEN
    RETURN NEW;
  END IF;

  -- Walk the parent_of graph from NEW.targetId; if we ever hit NEW.sourceId,
  -- we're creating a cycle.
  WITH RECURSIVE chain AS (
    SELECT NEW.target_id AS root
    UNION ALL
    SELECT wir.target_id
    FROM "WorkItemRelation" wir
    WHERE wir.relation = 'parent_of'
      AND wir.workspace_id = NEW.workspace_id
      AND wir.source_id = chain.root
  )
  SELECT EXISTS (
    SELECT 1 FROM chain WHERE root = NEW.source_id
  ) INTO has_cycle;

  IF has_cycle THEN
    RAISE EXCEPTION 'parent_of cycle detected (% -> %)', NEW.source_id, NEW.target_id;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS work_item_relation_no_parent_of_cycle ON "WorkItemRelation";
CREATE CONSTRAINT TRIGGER work_item_relation_no_parent_of_cycle
  AFTER INSERT OR UPDATE ON "WorkItemRelation"
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW
  EXECUTE FUNCTION orvix_assert_no_parent_of_cycle();

-- =============================================================================
-- 6. Merkle-style audit-log chain helper
-- =============================================================================
--
-- Stores each AuditLog row with a `root_hash` that chains the row payload
-- to the previous row's `root_hash`. Replication to S3 (with Object Lock)
-- is the external notarization step that customer / auditor can verify.

CREATE OR REPLACE FUNCTION orvix_compute_audit_chain(prev_hash text, payload jsonb)
RETURNS text AS $$
  SELECT encode(
    digest(
      coalesce(prev_hash, '') || jsonb_build_object('payload', payload)::text,
      'sha256'
    ),
    'hex'
  );
$$ LANGUAGE sql IMMUTABLE;

-- Removed automatic trigger chain computation on insert. We compute the
-- hash from the application server (after previous row read) so the chain
-- is portable and the DB role isn't trusted. The batcher computes:
--
--   SELECT COALESCE(
--     (SELECT "rootHash" FROM "AuditLog"
--       WHERE "workspaceId" = $1 ORDER BY "createdAt" DESC LIMIT 1),
--     ''
--   );
--
-- then computes the next root_hash, then INSERTs. This is the application
-- contract; this migration does not impose a DB-side trigger so the chain
-- is owned by the application layer (Phase 0 M0.4 telemetry surface
-- publishes a verifier).
